### ISSUE TITLE
Setup version control

### ISSUE THREAD

**Issue by barioto** [luizalabs/lasier#2]
Needing some sort of version control (with changelog).
Some examples would be [Towncrier](https://pypi.org/project/towncrier/) and [bumpversion](https://pypi.org/project/bumpversion/)

**Comment by drgarcia1986** [comment]
Hi, @barioto  what's up? 
I created #4  to solve half of this issue.
Now I have some doubts about `towncrier`, I think we won't suffer from "rebase troubles" for this project ('cause it's very simple), what do you think?

**Comment by barioto** [comment]
Fair enough.
I think the versioning method you chose is the best one considering
the "size" of this project.
